package com.example.sakura_flashcard.util

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Secure encryption utilities using Android Keystore.
 * 
 * Key Features:
 * - Uses Android Keystore for secure key storage (hardware-backed on supported devices)
 * - Keys are generated and stored securely, never exposed in memory
 * - Uses AES-256-GCM authenticated encryption
 * - Random IV is generated for each encryption operation
 * - IV is prepended to ciphertext for decryption
 * 
 * Security Improvements over hardcoded keys:
 * 1. Key is stored in hardware-backed secure element (TEE/StrongBox)
 * 2. Key cannot be extracted even with root access
 * 3. Each encryption uses a unique random IV
 * 4. GCM mode provides authentication (detects tampering)
 */
object CryptoUtils {
    
    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS = "sakura_crypto_key"
    private const val ALGORITHM = "AES/GCM/NoPadding"
    private const val GCM_TAG_LENGTH = 128  // bits
    private const val GCM_IV_LENGTH = 12    // bytes (recommended for GCM)
    
    /**
     * Get or create the secret key from Android Keystore.
     * 
     * The key is:
     * - Generated once and stored permanently in Keystore
     * - Hardware-backed on devices with TEE/StrongBox
     * - Cannot be extracted, only used for encrypt/decrypt operations
     */
    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
        keyStore.load(null)
        
        // Check if key already exists
        if (keyStore.containsAlias(KEY_ALIAS)) {
            val entry = keyStore.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry
            return entry.secretKey
        }
        
        // Generate new key
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER
        )
        
        val keyGenSpec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)  // AES-256
            .setRandomizedEncryptionRequired(true)  // Enforce random IV
            .build()
        
        keyGenerator.init(keyGenSpec)
        return keyGenerator.generateKey()
    }
    
    /**
     * Encrypt plaintext using AES-256-GCM.
     * 
     * Output format: [IV (12 bytes)][Ciphertext + Auth Tag]
     * The IV is prepended to the ciphertext for use during decryption.
     * 
     * @param plainText The string to encrypt
     * @return Base64-encoded string containing IV + ciphertext
     * @throws Exception if encryption fails
     */
    fun encrypt(plainText: String): String {
        val cipher = Cipher.getInstance(ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        
        // IV is automatically generated by Cipher (12 bytes for GCM)
        val iv = cipher.iv
        val encryptedBytes = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))
        
        // Combine IV + Ciphertext
        // Format: [IV (12 bytes)][Ciphertext + GCM Tag]
        val combined = ByteArray(iv.size + encryptedBytes.size)
        System.arraycopy(iv, 0, combined, 0, iv.size)
        System.arraycopy(encryptedBytes, 0, combined, iv.size, encryptedBytes.size)
        
        return Base64.encodeToString(combined, Base64.NO_WRAP)
    }
    
    /**
     * Decrypt ciphertext using AES-256-GCM.
     * 
     * Expected input format: [IV (12 bytes)][Ciphertext + Auth Tag]
     * 
     * @param encryptedText Base64-encoded string containing IV + ciphertext
     * @return The decrypted plaintext string
     * @throws Exception if decryption fails or authentication tag is invalid
     */
    fun decrypt(encryptedText: String): String {
        val combined = Base64.decode(encryptedText, Base64.DEFAULT)
        
        // Extract IV (first 12 bytes)
        val iv = combined.copyOfRange(0, GCM_IV_LENGTH)
        
        // Extract ciphertext (remaining bytes)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH, combined.size)
        
        val cipher = Cipher.getInstance(ALGORITHM)
        val gcmSpec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), gcmSpec)
        
        val decryptedBytes = cipher.doFinal(ciphertext)
        return String(decryptedBytes, Charsets.UTF_8)
    }
    
    /**
     * Check if a valid encryption key exists in Keystore.
     * 
     * @return true if key exists and is valid
     */
    fun hasValidKey(): Boolean {
        return try {
            val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
            keyStore.load(null)
            keyStore.containsAlias(KEY_ALIAS)
        } catch (e: Exception) {
            false
        }
    }
    
    /**
     * Delete the encryption key from Keystore.
     * 
     * WARNING: All data encrypted with this key will become unrecoverable!
     * Only use this for account deletion or key rotation scenarios.
     */
    fun deleteKey() {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
        keyStore.load(null)
        if (keyStore.containsAlias(KEY_ALIAS)) {
            keyStore.deleteEntry(KEY_ALIAS)
        }
    }
    
    /**
     * Rotate the encryption key.
     * 
     * This method:
     * 1. Deletes the old key
     * 2. Generates a new key
     * 
     * WARNING: Data encrypted with old key will not be recoverable!
     * Call this only after re-encrypting all data with the new key.
     */
    fun rotateKey() {
        deleteKey()
        getOrCreateKey()  // Generate new key
    }
}
